# pvc-template.yaml (kubevirt-vms/pvc-template.yaml)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-vm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
